pipeline{
    agent any
    stages{
        stage('check-2'){
            steps{
                sh 'echo "hello"'
                sh 'ls'
                sh 'cd ~'
                sh 'pwd'
            }
        }
    }
}
