pipeline{
    agent any
    environment{
        region = 'ap-south-1'
        ecr_repo = 'payment-service'
        aws_account = '985151713154'
        ecr_url = '.dkr.ecr.ap-south-1.amazonaws.com/payment-service'
        old_tag = '42'
        tag = "${BUILD_NUMBER}"
    }
    stages{
        stage('file validation'){
            steps{
                sh 'pwd'
                sh 'ls'
                sh 'find -name "*.tf"'
            }
        }
        stage('terraform version'){
            steps{
                sh 'terraform version'
            }
        }
        stage('fmt check'){
            steps{
                sh 'cd terraform/aws-network'
                sh 'terraform fmt --check'
                sh 'terraform init'
                sh 'terraform validate'
            }
        }
        stage('docker verify'){
            steps{
                sh 'docker --version'
            }
        }
        stage('docker login'){
            steps{
                sh '''
                set -e
                aws ecr get-login-password --region ${region}| docker login --username AWS --password-stdin ${aws_account}${ecr_url}
                echo "login successfull"
                '''
            }
        }
        stage('docker build'){
            steps{
                sh 'cd'
                sh 'cd payment-app'
                sh 'docker build payment-app/ -t "${aws_account}${ecr_url}:${tag}"'
                sh 'docker images'
                sh 'docker push "${aws_account}${ecr_url}:${tag}"'
            }
        }
        stage('variable pick'){
            steps{
                sh 'echo "${aws_account}"'
                sh 'echo "${aws_account}${ecr_url}"'
                sh 'echo "${tag}"'
            }
        }
        stage('image show'){
            steps{
            sh 'echo "${aws_account}${ecr_url}:${tag}"'
            }
        }
        stage('file check'){
            steps{
                sh '''
                    if [ -f "payment-helm/templates/configmap.yaml" ] && [ -f "payment-helm/templates/deployment.yaml" ] && [ -f "payment-helm/templates/service.yaml" ]; then
                        echo "file exists"
                    else 
                        echo "Dockerfile not found"
                        exit 1
                    fi
                    '''
            }
        }
        stage('config check'){
            steps{
                sh 'kubectl version'
                sh 'aws --version'
                sh 'aws eks list-clusters --region "$region"'
            }
        }
        stage('deploy-check'){
            steps{
                sh 'aws eks update-kubeconfig --region "${region}" --name production-eks'
                sh 'kubectl get pods'
                sh 'kubectl get nodes'
            }
        }
        stage('deploy'){
            steps{
                sh 'sed -i -E "s|^[[:space:]]*tag:.*|  tag: \\"${BUILD_NUMBER}\\"|" payment-helm/values.yaml'
                sh 'cat payment-helm/values.yaml'
                sh 'helm upgrade payment-service payment-helm/ -n payment-app'
                sh 'helm list -n payment-app'
                sh 'kubectl get pods -n payment-app'
            }
        }
        stage('push'){
            steps{
		sh 'git init'
                sh 'git fetch origin main'
                sh 'git checkout -B main origin/main'
                sh 'git add payment-helm/values.yaml'
                sh 'git commit -m "new build"'
                sh 'git push origin main'
            }
        }
    }
}

