pipeline{
    agent any
    environment{
        region ='ap-south-1'
        ecr-repo ='payment-service'
        aws-account ='985151713154'
        ecr-url ='.dkr.ecr.ap-south-1.amazonaws.com/payment-service'
        tag ="${BUILD_NUMBER}"
    }
    stages{
        stage('file validation'){
            steps{
                sh 'pwd'
                sh 'ls'
                sh 'find -name "*.tf"'
            }
        }
        stage('terraform version'){
            steps{
                sh 'terraform version'
            }
        }
        stage('fmt check'){
            steps{
                sh 'cd terraform/aws-network'
                sh 'terraform fmt --check'
                sh 'terraform init'
                sh 'terraform validate'
            }
        }
        stage('docker verify'){
            steps{
                sh 'docker --version'
            }
        }
        stage('docker build'){
            steps{
                sh 'cd'
                sh 'cd payment-app'
                sh 'docker build payment-app/ -t "985151713154.dkr.ecr.ap-south-1.amazonaws.com/payment-service:v111"'
                sh 'docker images'
            }
        }
        stage('variable pick'){
            steps{
                sh 'echo "${aws-account}"'
                sh 'echo "${aws-account}${ecr-url}"'
            }
        }
    }
}
